# Generated by Django 4.2.3 on 2023-07-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("heroes", "0002_alter_pcharacter_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pcharacter",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
